### ISSUE TITLE
Error popping really often

### ISSUE THREAD

**Issue by Alex-Blanes** [catgirlfighter/RimWorld_CommonSense#13] opened 2020-03-05 23:24 UTC
Hi,
This is from my first times adding a problem to a mod. Anything to improve is welcome.
I added your mod to my mod list. I debugged an error that ends in its mod where this error appears very frequently (several times in the same second).
Here is the [log](https://textuploader.com/16vuh).
Maybe my [modlist](https://textuploader.com/16vuh) makes some incompatibilities with your mod.
I have no more information on my hands of this error.

On the other hand, I have seen that in the configuration of mods a section should appear to configure your mod. It does not appear to me.

It may also be because I am using its latest updated version on git and it is not a release version.
If so, my apologies for being muddled.

**Comment by catgirlfighter** [comment] 2020-03-06 11:01
Hello!
Your log and modlist are the same link, could you please update that? :)
I'll check later today if I've updated everything on github. Sometimes I forget to commit changes, it maybe the case.

**Comment by catgirlfighter** [comment] 2020-03-06 19:42
It appears that repositories are up to date.

**Comment by Alex-Blanes** [comment] 2020-03-09 21:53
Sorry for the delay. Some days ago, I removed your mod from the mod list and I added some more and removed others. Today I added back and It keeps showing the same exception. 
Exception in RimWorld.ThinkNode_ConditionalNeedPercentageAbove TryIssueJobPackage: System.MissingMethodException: bool RimWorld.FoodUtility.TryFindBestFoodSourceFor(Verse.Pawn,Verse.Pawn,bool,Verse.Thing&,Verse.ThingDef&,bool,bool,bool,bool,bool,bool,bool,bool,RimWorld.FoodPreferability)
This is the correct [log](https://gist.github.com/HugsLibRecordKeeper/081786b6b0a41b8df07f1d2d7f202b19).

**Comment by catgirlfighter** [comment] 2020-03-10 10:37
Alright, now I have stuff to work with, thanks.

**Comment by catgirlfighter** [comment] 2020-03-10 20:29
Everything leads to the conclusion that you've managed to download an unstable version of the mod, or more accurately one of those versions when Harmony was unstable, and all those errors was exactly what happened with it. My mod was re-compiled with another framework and better suited for fresher version of Harmony, so basically try to re-download the mod and test it again :/
It's worse if you don't use steam, because now you have to manually check if ANY of the mods use older harmony, but don't have a dependency on a Harmony mod, since even one mod with broken version of Harmony gonna break all other Harmony using mods.

**Comment by Alex-Blanes** [comment] 2020-03-11 20:17
Thanks in advance.
I will try to re-download your mod and I will tell you what happens.
I doubt is a Harmony problem because from what I understand If I can keep playing means that there is no issue with harmony outdated library.
If some mod were using the antique version It would break the game.
But if you are saying so maybe you have the reason. I'm still not a rimworld mod developer.

**Comment by catgirlfighter** [comment] 2020-03-12 16:27
Nah, those two problems happened when I used Harmony 2.0.0.1 and disappeared when I replaced it with Harmony 2.0.0.7, and I got the info about problems from a guy that told me in a mod comment about Harmony problems :) If it not gonna help you, then I have no clue, what else could it be (I can't reproduce this) and your save game will be required.

**Comment by mohas** [comment] 2020-04-16 07:38
Hi, I have the same issue Here is the [log file](https://github.com/catgirlfighter/RimWorld_CommonSense/files/4485552/Player.log), the error keeps getting reproduced so I removed all instances from log but 1, modlist is included in the log

**Comment by catgirlfighter** [comment] 2021-04-17 16:25
If this issue is still actual, create a new issue. Closing current one due to age.

**Closed as completed by catgirlfighter** 2021-04-17 16:25 UTC
